#pragma once

#include <stdexcept>
#include <string>
#include <fstream>
#include <sstream>
#include <iostream>
#include <istream>
#include <exception>
#include <assert.h>
#include <vector>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <cstdlib>

#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include "stb_image.h"
#include "glm/glm.hpp"
#include "glm/gtc/matrix_transform.hpp"
#include "glm/gtc/type_ptr.hpp"
#include "glm/gtx/string_cast.hpp"
#include <glm/gtx/matrix_decompose.hpp>
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include "assimp/Importer.hpp"
#include "assimp/scene.h"
#include "assimp/postprocess.h"
//s#include "Scatter.h"
